package telas;

import java.awt.Toolkit;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 * A classe TelaPrincipal representa uma interface gráfica que possibilita a
 * interação, pelo usuário, com todas as funcionalidades do sistema.
 *
 * @author Alisson Jaques
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Campos da classe
     */
    private TelaDeLogin telaLogin;      // a tela de login
    private TelaOcorrencias telaOcorrencias;// a tela de índice invertido
    private TelaBuscaBooleana telaDocumentos;
    private TelaBuscaEspacoVetorial telaEspacoVetorial;
    private TelaBuscaModeloProbabilista telaBuscaProbabilista;
    private TelaBuscaProbDocRel telaBuscaProbabilistaRelevantes;

    /**
     * Creates new form TelaPrincipal
     * @throws java.lang.ClassNotFoundException
     * @throws java.lang.InstantiationException
     * @throws java.lang.IllegalAccessException
     * @throws javax.swing.UnsupportedLookAndFeelException
     */
    public TelaPrincipal() throws ClassNotFoundException, InstantiationException, 
            IllegalAccessException, UnsupportedLookAndFeelException {
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("src\\img\\auditoria_32.png"));
        initComponents();
        String lookAndFeelClassName = UIManager.getSystemLookAndFeelClassName();
        UIManager.setLookAndFeel(lookAndFeelClassName);
    }

    /**
     * O método centralizarJInternalFrame(JInternalFrame) centraliza o frame
     * passado como argumento na tela da aplicação.
     *
     * @param frame uma intância da classe JInternalFrame a ser centralizada na
     * aplicação.
     */
    private void centralizarJInternalFrame(JInternalFrame frame) {

        int lDesk = getJdpPrincipal().getWidth();
        int aDesk = getJdpPrincipal().getHeight();

        int lFrame = frame.getWidth();
        int aFrame = frame.getHeight();

        frame.setLocation(lDesk / 2 - lFrame / 2, aDesk / 2 - aFrame / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpPrincipal = new javax.swing.JDesktopPane();
        jlOrgImg = new javax.swing.JLabel();
        jmbMenus = new javax.swing.JMenuBar();
        jmLogin = new javax.swing.JMenu();
        jmiLogin = new javax.swing.JMenuItem();
        jmiSair = new javax.swing.JMenuItem();
        jmIndiceInvertido = new javax.swing.JMenu();
        jmiGerarIndiceInvertido = new javax.swing.JMenuItem();
        jmconsuta = new javax.swing.JMenu();
        jmigerarconsulta = new javax.swing.JMenuItem();
        jmPesquisaVetorial = new javax.swing.JMenuItem();
        jmiBuscaProbabilista = new javax.swing.JMenuItem();
        jmiDocRelevantes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Organização e Recuperação da Informação");

        jdpPrincipal.setBackground(new java.awt.Color(0, 0, 51));
        jdpPrincipal.setPreferredSize(new java.awt.Dimension(856, 751));

        jlOrgImg.setBackground(new java.awt.Color(0, 0, 51));
        jlOrgImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/org3.jpg"))); // NOI18N

        jdpPrincipal.setLayer(jlOrgImg, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpPrincipalLayout = new javax.swing.GroupLayout(jdpPrincipal);
        jdpPrincipal.setLayout(jdpPrincipalLayout);
        jdpPrincipalLayout.setHorizontalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdpPrincipalLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jlOrgImg)
                .addGap(21, 21, 21))
        );
        jdpPrincipalLayout.setVerticalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdpPrincipalLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jlOrgImg)
                .addGap(69, 69, 69))
        );

        jmLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PessoaFisica.png"))); // NOI18N
        jmLogin.setText("Login");
        jmLogin.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jmiLogin.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmiLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user32.png"))); // NOI18N
        jmiLogin.setText("Login");
        jmiLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLoginActionPerformed(evt);
            }
        });
        jmLogin.add(jmiLogin);

        jmiSair.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmiSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close_32.png"))); // NOI18N
        jmiSair.setText("Sair");
        jmiSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSairActionPerformed(evt);
            }
        });
        jmLogin.add(jmiSair);

        jmbMenus.add(jmLogin);

        jmIndiceInvertido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh_1.png"))); // NOI18N
        jmIndiceInvertido.setText("Índice Invertido");
        jmIndiceInvertido.setEnabled(false);
        jmIndiceInvertido.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jmIndiceInvertido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmIndiceInvertidoActionPerformed(evt);
            }
        });

        jmiGerarIndiceInvertido.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmiGerarIndiceInvertido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/report_32.png"))); // NOI18N
        jmiGerarIndiceInvertido.setText("Gerar");
        jmiGerarIndiceInvertido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGerarIndiceInvertidoActionPerformed(evt);
            }
        });
        jmIndiceInvertido.add(jmiGerarIndiceInvertido);

        jmbMenus.add(jmIndiceInvertido);

        jmconsuta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisa32.png"))); // NOI18N
        jmconsuta.setText("Consulta");
        jmconsuta.setEnabled(false);
        jmconsuta.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jmigerarconsulta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmigerarconsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/srch_32.png"))); // NOI18N
        jmigerarconsulta.setText("Pesquisa Booleana");
        jmigerarconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmigerarconsultaActionPerformed(evt);
            }
        });
        jmconsuta.add(jmigerarconsulta);

        jmPesquisaVetorial.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmPesquisaVetorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/view_32.png"))); // NOI18N
        jmPesquisaVetorial.setText("Pesquisa Modelo Vetorial");
        jmPesquisaVetorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPesquisaVetorialActionPerformed(evt);
            }
        });
        jmconsuta.add(jmPesquisaVetorial);

        jmiBuscaProbabilista.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmiBuscaProbabilista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/srch_32.png"))); // NOI18N
        jmiBuscaProbabilista.setText("Pesquisa Modelo Probabilista");
        jmiBuscaProbabilista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBuscaProbabilistaActionPerformed(evt);
            }
        });
        jmconsuta.add(jmiBuscaProbabilista);

        jmiDocRelevantes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmiDocRelevantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/view_32.png"))); // NOI18N
        jmiDocRelevantes.setText("Pesquisa Probabilista com Documentos Relevantes");
        jmiDocRelevantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDocRelevantesActionPerformed(evt);
            }
        });
        jmconsuta.add(jmiDocRelevantes);

        jmbMenus.add(jmconsuta);

        setJMenuBar(jmbMenus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLoginActionPerformed
        TelaDeLogin tl = new TelaDeLogin(this, true);
        tl.setVisible(true);
    }//GEN-LAST:event_jmiLoginActionPerformed

    private void jmiSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSairActionPerformed
        int op = JOptionPane.showConfirmDialog(this, "Deseja mesmo sair do sistema?", "Sair", JOptionPane.OK_CANCEL_OPTION);

        if (op == 0) {
            dispose();
        }
    }//GEN-LAST:event_jmiSairActionPerformed

    private void jmiGerarIndiceInvertidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGerarIndiceInvertidoActionPerformed
        if (getTelaOcorrencias() == null) {
            setTelaOcorrencias(new TelaOcorrencias());
            getJdpPrincipal().add(getTelaOcorrencias());
            getTelaOcorrencias().setVisible(true);
            centralizarJInternalFrame(getTelaOcorrencias());
        } else if (getTelaOcorrencias() != null) {
            if (getTelaOcorrencias().isClosed()) {
                setTelaOcorrencias(new TelaOcorrencias());
                getJdpPrincipal().add(getTelaOcorrencias());
                getTelaOcorrencias().setVisible(true);
                centralizarJInternalFrame(getTelaOcorrencias());
            }
        }
    }//GEN-LAST:event_jmiGerarIndiceInvertidoActionPerformed

    private void jmIndiceInvertidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmIndiceInvertidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmIndiceInvertidoActionPerformed

    private void jmigerarconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmigerarconsultaActionPerformed
        if (getTelaDocumentos() == null) {
            setTelaDocumentos(new TelaBuscaBooleana());
            getJdpPrincipal().add(getTelaDocumentos());
            getTelaDocumentos().setVisible(true);
            centralizarJInternalFrame(getTelaDocumentos());
        } else if (getTelaDocumentos() != null) {
            if (getTelaDocumentos().isClosed()) {
                setTelaDocumentos(new TelaBuscaBooleana());
                getJdpPrincipal().add(getTelaDocumentos());
                getTelaDocumentos().setVisible(true);
                centralizarJInternalFrame(getTelaDocumentos());
            }
        }
    }//GEN-LAST:event_jmigerarconsultaActionPerformed

    private void jmPesquisaVetorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPesquisaVetorialActionPerformed
        if (getTelaEspacoVetorial() == null) {
            setTelaEspacoVetorial(new TelaBuscaEspacoVetorial());
            getJdpPrincipal().add(getTelaEspacoVetorial());
            getTelaEspacoVetorial().setVisible(true);
            centralizarJInternalFrame(getTelaEspacoVetorial());
        } else if (getTelaEspacoVetorial() != null) {
            if (getTelaEspacoVetorial().isClosed()) {
                setTelaEspacoVetorial(new TelaBuscaEspacoVetorial());
                getJdpPrincipal().add(getTelaEspacoVetorial());
                getTelaEspacoVetorial().setVisible(true);
                centralizarJInternalFrame(getTelaEspacoVetorial());
            }
        }
    }//GEN-LAST:event_jmPesquisaVetorialActionPerformed

    private void jmiBuscaProbabilistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBuscaProbabilistaActionPerformed
        if (getTelaBuscaProbabilista() == null) {
            setTelaBuscaProbabilista(new TelaBuscaModeloProbabilista());
            getJdpPrincipal().add(getTelaBuscaProbabilista());
            getTelaBuscaProbabilista().setVisible(true);
            centralizarJInternalFrame(getTelaBuscaProbabilista());
        } else if (getTelaBuscaProbabilista() != null) {
            if (getTelaBuscaProbabilista().isClosed()) {
                setTelaBuscaProbabilista(new TelaBuscaModeloProbabilista());
                getJdpPrincipal().add(getTelaBuscaProbabilista());
                getTelaBuscaProbabilista().setVisible(true);
                centralizarJInternalFrame(getTelaBuscaProbabilista());
            }
        }
    }//GEN-LAST:event_jmiBuscaProbabilistaActionPerformed

    private void jmiDocRelevantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDocRelevantesActionPerformed
        if (getTelaBuscaProbabilistaRelevantes() == null) {
            setTelaBuscaProbabilistaRelevantes(new TelaBuscaProbDocRel());
            getJdpPrincipal().add(getTelaBuscaProbabilistaRelevantes());
            getTelaBuscaProbabilistaRelevantes().setVisible(true);
            centralizarJInternalFrame(getTelaBuscaProbabilistaRelevantes());
        } else if (getTelaBuscaProbabilistaRelevantes() != null) {
            if (getTelaBuscaProbabilistaRelevantes().isClosed()) {
                setTelaBuscaProbabilistaRelevantes(new TelaBuscaProbDocRel());
                getJdpPrincipal().add(getTelaBuscaProbabilistaRelevantes());
                getTelaBuscaProbabilistaRelevantes().setVisible(true);
                centralizarJInternalFrame(getTelaBuscaProbabilistaRelevantes());
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_jmiDocRelevantesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane jdpPrincipal;
    private javax.swing.JLabel jlOrgImg;
    private javax.swing.JMenu jmIndiceInvertido;
    private javax.swing.JMenu jmLogin;
    private javax.swing.JMenuItem jmPesquisaVetorial;
    private javax.swing.JMenuBar jmbMenus;
    private javax.swing.JMenu jmconsuta;
    private javax.swing.JMenuItem jmiBuscaProbabilista;
    private javax.swing.JMenuItem jmiDocRelevantes;
    private javax.swing.JMenuItem jmiGerarIndiceInvertido;
    private javax.swing.JMenuItem jmiLogin;
    private javax.swing.JMenuItem jmiSair;
    private javax.swing.JMenuItem jmigerarconsulta;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the telaBuscaProbabilistaRelevantes
     */
    public TelaBuscaProbDocRel getTelaBuscaProbabilistaRelevantes() {
        return telaBuscaProbabilistaRelevantes;
    }

    /**
     * @param telaBuscaProbabilistaRelevantes the
     * telaBuscaProbabilistaRelevantes to set
     */
    public void setTelaBuscaProbabilistaRelevantes(TelaBuscaProbDocRel telaBuscaProbabilistaRelevantes) {
        this.telaBuscaProbabilistaRelevantes = telaBuscaProbabilistaRelevantes;
    }

    /**
     * @return the telaBuscaProbabilista
     */
    public TelaBuscaModeloProbabilista getTelaBuscaProbabilista() {
        return telaBuscaProbabilista;
    }

    /**
     * @param telaBuscaProbabilista the telaBuscaProbabilista to set
     */
    public void setTelaBuscaProbabilista(TelaBuscaModeloProbabilista telaBuscaProbabilista) {
        this.telaBuscaProbabilista = telaBuscaProbabilista;
    }

    /**
     * @return the telaLogin
     */
    public TelaDeLogin getTelaLogin() {
        return telaLogin;
    }

    /**
     * @param telaLogin the telaLogin to set
     */
    public void setTelaLogin(TelaDeLogin telaLogin) {
        this.telaLogin = telaLogin;
    }

    /**
     * @return the telaOcorrencias
     */
    public TelaOcorrencias getTelaOcorrencias() {
        return telaOcorrencias;
    }

    /**
     * @param telaOcorrencias the telaOcorrencias to set
     */
    public void setTelaOcorrencias(TelaOcorrencias telaOcorrencias) {
        this.telaOcorrencias = telaOcorrencias;
    }

    /**
     * @return the jdpPrincipal
     */
    public javax.swing.JDesktopPane getJdpPrincipal() {
        return jdpPrincipal;
    }

    /**
     * @param jdpPrincipal the jdpPrincipal to set
     */
    public void setJdpPrincipal(javax.swing.JDesktopPane jdpPrincipal) {
        this.jdpPrincipal = jdpPrincipal;
    }

    /**
     * @return the jmIndiceInvertido
     */
    public javax.swing.JMenu getJmIndiceInvertido() {
        return jmIndiceInvertido;
    }

    /**
     * @param jmIndiceInvertido the jmIndiceInvertido to set
     */
    public void setJmIndiceInvertido(javax.swing.JMenu jmIndiceInvertido) {
        this.jmIndiceInvertido = jmIndiceInvertido;
    }

    /**
     * @return the jmLogin
     */
    public javax.swing.JMenu getJmLogin() {
        return jmLogin;
    }

    /**
     * @param jmLogin the jmLogin to set
     */
    public void setJmLogin(javax.swing.JMenu jmLogin) {
        this.jmLogin = jmLogin;
    }

    /**
     * @return the jmbMenus
     */
    public javax.swing.JMenuBar getJmbMenus() {
        return jmbMenus;
    }

    /**
     * @param jmbMenus the jmbMenus to set
     */
    public void setJmbMenus(javax.swing.JMenuBar jmbMenus) {
        this.jmbMenus = jmbMenus;
    }

    /**
     * @return the jmiGerarIndiceInvertido
     */
    public javax.swing.JMenuItem getJmiGerarIndiceInvertido() {
        return jmiGerarIndiceInvertido;
    }

    /**
     * @param jmiGerarIndiceInvertido the jmiGerarIndiceInvertido to set
     */
    public void setJmiGerarIndiceInvertido(javax.swing.JMenuItem jmiGerarIndiceInvertido) {
        this.jmiGerarIndiceInvertido = jmiGerarIndiceInvertido;
    }

    /**
     * @return the jmiLogin
     */
    public javax.swing.JMenuItem getJmiLogin() {
        return jmiLogin;
    }

    /**
     * @param jmiLogin the jmiLogin to set
     */
    public void setJmiLogin(javax.swing.JMenuItem jmiLogin) {
        this.jmiLogin = jmiLogin;
    }

    /**
     * @return the jmiSair
     */
    public javax.swing.JMenuItem getJmiSair() {
        return jmiSair;
    }

    /**
     * @param jmiSair the jmiSair to set
     */
    public void setJmiSair(javax.swing.JMenuItem jmiSair) {
        this.jmiSair = jmiSair;
    }

    /**
     * @return the telaDocumentos
     */
    public TelaBuscaBooleana getTelaDocumentos() {
        return telaDocumentos;
    }

    /**
     * @param telaDocumentos the telaDocumentos to set
     */
    public void setTelaDocumentos(TelaBuscaBooleana telaDocumentos) {
        this.telaDocumentos = telaDocumentos;
    }

    /**
     * @return the jmconsuta
     */
    public javax.swing.JMenu getJmconsuta() {
        return jmconsuta;
    }

    /**
     * @param jmconsuta the jmconsuta to set
     */
    public void setJmconsuta(javax.swing.JMenu jmconsuta) {
        this.jmconsuta = jmconsuta;
    }

    /**
     * @return the jmigerarconsulta
     */
    public javax.swing.JMenuItem getJmigerarconsulta() {
        return jmigerarconsulta;
    }

    /**
     * @param jmigerarconsulta the jmigerarconsulta to set
     */
    public void setJmigerarconsulta(javax.swing.JMenuItem jmigerarconsulta) {
        this.jmigerarconsulta = jmigerarconsulta;
    }

    /**
     * @return the telaEspacoVetorial
     */
    public TelaBuscaEspacoVetorial getTelaEspacoVetorial() {
        return telaEspacoVetorial;
    }

    /**
     * @param telaEspacoVetorial the telaEspacoVetorial to set
     */
    public void setTelaEspacoVetorial(TelaBuscaEspacoVetorial telaEspacoVetorial) {
        this.telaEspacoVetorial = telaEspacoVetorial;
    }
}
